
package br.edu.ifsul.cc.lpoo.cs.gui.jogador;

/**
 *
 * @author telmo
 */
public class JPanelFuncionarioListagem extends javax.swing.JPanel {

    /**
     * Creates new form JPanelJogadorListagem
     */
    public JPanelFuncionarioListagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFiltro = new javax.swing.JPanel();
        lblFiltro = new javax.swing.JLabel();
        txtfFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        pnlSul = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        scpRolagem = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lblFiltro.setText("Filtrar por CPF ou Nome:");
        pnlFiltro.add(lblFiltro);

        txtfFiltro.setColumns(10);
        pnlFiltro.add(txtfFiltro);

        btnFiltrar.setText("Filtrar");
        pnlFiltro.add(btnFiltrar);

        add(pnlFiltro, java.awt.BorderLayout.PAGE_START);

        btnNovo.setText("Novo");
        pnlSul.add(btnNovo);

        btnEditar.setText("Editar");
        pnlSul.add(btnEditar);

        btnRemover.setText("Remover");
        pnlSul.add(btnRemover);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "N°. CTPS", "N°. PIS", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpRolagem.setViewportView(jTable1);

        pnlCentro.add(scpRolagem, java.awt.BorderLayout.CENTER);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlFiltro;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JScrollPane scpRolagem;
    private javax.swing.JTextField txtfFiltro;
    // End of variables declaration//GEN-END:variables
}
